"""empty message

Revision ID: 67c706e35d46
Revises: ca5cb5202f8a
Create Date: 2026-01-11 18:52:30.892533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c706e35d46'
down_revision: Union[str, Sequence[str], None] = 'ca5cb5202f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_media', sa.Column('project_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'project_media', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_media', type_='foreignkey')
    op.drop_column('project_media', 'project_id')
    # ### end Alembic commands ###
