"""empty message

Revision ID: 9f407d7c3800
Revises: 239dd921e801
Create Date: 2026-01-11 23:24:07.932327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f407d7c3800'
down_revision: Union[str, Sequence[str], None] = '239dd921e801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_media', sa.Column('size', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_media', 'size')
    # ### end Alembic commands ###
