"""empty message

Revision ID: d003aaba5033
Revises: 0fddbbc00627
Create Date: 2026-01-13 04:30:37.170488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd003aaba5033'
down_revision: Union[str, Sequence[str], None] = '0fddbbc00627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenes', 'media_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenes', 'media_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
